repos:
  - hooks:
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: destroyed-symlinks
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: fix-encoding-pragma
        args:
          - --remove
      - id: mixed-line-ending
      - args:
          - '--maxkb=1024'
        id: check-added-large-files
      - args:
          - '--markdown-linebreak-ext=md'
        id: trailing-whitespace
      - id: check-symlinks
      - args:
          - '--allow-multiple-documents'
        id: check-yaml
      - args:
          - '--maxkb=1024'
        id: check-added-large-files
      - id: requirements-txt-fixer
      - id: check-ast
    repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.0.1
  - repo: https://github.com/ambv/black
    rev: 21.7b0
    hooks:
    - id: black
      args: [--line-length=130]
      language_version: python3.9
  # - repo: https://gitlab.com/pycqa/flake8
  #   rev: 3.9.2
  #   hooks:
  #   - id: flake8
  #     args: [--max-line-length=130]
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.6.0
    hooks:
    - id: reorder-python-imports
      args: [--application-directories, '.:src', --py36-plus]
